stages:
  - build
  - deploy

image:
  node@sha256:d1b3088a17b138b9b6b23838943d932b7fef4fe80300c4e775c7e541d39b512f
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  PRODUCTION_DOMAIN : xini-surveys-prod.surge.sh
  STAGE_DOMAIN: xini-surveys.surge.sh

build:
  stage: build
  only:
    - master
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm install -g @angular/cli
    - ng build
  artifacts:
    paths:
      - ./dist

deploy:
  stage: deploy
  only:
    - master
  script:
    - npm install --global surge
    - test -f ./dist/survey-management/index.html
    - echo $?
    - surge --project ./dist/survey-management --domain $STAGE_DOMAIN
